### ISSUE TITLE
CMAKE_CUDA_ARCHITECTURES must be valid if set.

### ISSUE THREAD

**Issue by Seagullflysxt** [bycloudai/instant-ngp-Windows#4]
Hi! Thanks for your work:)
**When I run cmake . -B build,I got this:**
```shell
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.17763.
CMake Error at E:/Software/cmake/share/cmake-3.23/Modules/CMakeDetermineCUDACompiler.cmake:311 (message):
  CMAKE_CUDA_ARCHITECTURES must be valid if set.
Call Stack (most recent call first):
  CMakeLists.txt:11 (project)

-- Configuring incomplete, errors occurred!
See also "D:/graduate/nerf/instant-ngp-master/build/CMakeFiles/CMakeOutput.log".
See also "D:/graduate/nerf/instant-ngp-master/build/CMakeFiles/CMakeError.log".
```
I searched this online, **and tried these 2 things below:**

1.Add **set(CMAKE_CUDA_ARCHITECTURES 48)**  in cmakelists
2. Use cmake . -B build -DCMAKE_CUDA_COMPILER=E:\Software\cuda\bin\nvcc -DTCNN_CUDA_ARCHITECTURES=61
 
But they didn't work

**Comment by bycloudai** [comment]
are you sure your CUDA architecture is compatible with 48?
you can check with `nvcc --list-gpu-arch` and `nvcc --list-gpu-code` 
maybe set to one that you have would work

**Comment by Seagullflysxt** [comment]
> 

Thanks for your reply:)
I uninstalled cuda and installed it from scratch, now cmake .B build can run successfully,but when I step to next command, I encounterd another problem
Like some include file can't be found, like unordered map 
I think it might be something wrong with msvc,so I'm going to reinstall msvc and see what happens


update：
Thanks for your detailed description so lot!!
Now everything works fine!
Great great thanks to you!
